theme: jekyll-theme-architect
title: ML For Systems
google_analytics: true
description: Workshop on ML for Systems at NeurIPS 2021, December 12th, Zoomville
workshop_name: neurips2021
mini_title: Current (2021)
