theme: jekyll-theme-architect
title: ML For Systems
google_analytics: true
description: Workshop on ML for Systems at NeurIPS 2020, December 12th, Zoomville
workshop_name: neurips2020
mini_title: Current (2020)
